name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v23
        uses: actions/setup-node@v4
        with:
          node-version: 23.x # Using a more flexible version specifier
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type Check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start dev server for Playwright tests
        run: |
          echo "Attempting to start Vite dev server in background..."
          npm run dev &
          echo "Vite dev server process initiated."
          sleep 5 # Give it a moment to spawn before wait-on checks
        env:
          NODE_ENV: development # Ensure dev server starts

      - name: Wait for dev server
        run: npx wait-on http://localhost:5173 -t 120000 # Wait for 120 seconds

      - name: Run Playwright tests
        run: npx playwright test

      - name: Stop dev server
        if: always() # Always run this step to ensure server is stopped
        run: |
          PID=$(pgrep -f "vite")
          if [ -n "$PID" ]; then
            kill $PID
            echo "Killed Vite dev server (PID: $PID)"
          else
            echo "Vite dev server not found or already stopped."
          fi

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
