name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/template-app

      - name: Run tests
        run: npm test
        working-directory: ./packages/template-app

      - name: Type check
        run: npm run type-check
        working-directory: ./packages/template-app

      - name: Build project
        run: npm run build
        working-directory: ./packages/template-app

      - name: Prepare 404 page for SPA
        run: cp packages/template-app/dist/index.html packages/template-app/dist/404.html

      - name: Add .nojekyll
        run: touch packages/template-app/dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/template-app/dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
